from pathlib import Path

PAPER_ID = "p11_vccfinder_finding_potential_vulnerabilities_in_open_source_projects_to_assist_code_audits_2015"
PAPER_DIR = Path(r"E:\AI\Agent\workflow\Paper\reference") / PAPER_ID
ANALYSIS = PAPER_DIR / "analysis"
PDF_PATH = r"E:\AI\Agent\workflow\Replication\BaseLine(Vulnerability-affected versions identification How far are we)\Direct_Comparison_Papers(Baseline_Paper+Code)\VCCFinder\VCCFinder：Finding Potential Vulnerabilities in Open-Source Projects to Assist Code Audits.pdf"
SOURCE_PATH = r"E:\AI\Agent\workflow\Replication\BaseLine(Vulnerability-affected versions identification How far are we)\Direct_Comparison_Papers(Baseline_Paper+Code)\VCCFinder\VCCFinder"

common = f"""Paper ID: {PAPER_ID}
Title: VCCFinder: Finding Potential Vulnerabilities in Open-Source Projects to Assist Code Audits
PDF Path: {PDF_PATH}
Source Path: {SOURCE_PATH}
Analysis Mode: PDF evidence + static source/artifact inspection only
Runtime Status: [EXECUTION NOT REQUESTED]

"""

files = {
"00_meta.txt": common + """Venue / Year: CCS 2015
Authors: Henning Perl; Sergej Dechand; Matthew Smith; Daniel Arp; Fabian Yamaguchi; Konrad Rieck; Sascha Fahl; Yasemin Acar
Artifact Type: Type B, local source code is present; full benchmark database/model/web service artifacts are not present in the observed local source root. [NEEDS ARTIFACT]
Input Files:
- PDF: original local PDF path above
- Source: local VCCFinder directory above
- Raw extraction: raw_extraction/full_text.txt, page_text/, section_text/, tables/, figures/
Source / Artifact Path: source path above
Analysis Status: completed with known table/figure/layout/citation/artifact gaps
Agent Index Status: to be regenerated by build_agent_index.py after analysis
Main Topic: prioritizing code audits by learning to identify vulnerability-contributing commits from code metrics and repository metadata.
Why This Paper Is Relevant: It is directly relevant to vulnerability-introducing commit identification, VCC database construction, SZZ-style blame heuristics, and ML-assisted vulnerability triage.
Citation Metadata Status: title/authors/venue/year/DOI extracted from PDF text; still marked [NEEDS CITATION VERIFICATION] before BibTeX use.
Missing Evidence: precise table repair, exact figure extraction, full artifact/database/model, README/dependency documentation, runtime reproduction.
""",
"01_abstract.txt": common + """Problem: Security audits cannot keep pace with the amount of code and expertise required, and metric-only tools such as Flawfinder generate too many false positives.
Gap: Existing code metric tools flag dangerous-looking code but leave overwhelming manual review effort.
Core Idea: Combine code metric analysis with repository metadata, then train a classifier to rank commits for human audit.
Method: Build a CVE-to-GitHub vulnerable commit database, derive vulnerability-contributing commits, extract heterogeneous features, and train an SVM classifier.
Evaluation Setup: The abstract claims comparison against Flawfinder and qualitative/quantitative analysis; exact numbers require table/figure repair. [NEEDS TABLE REPAIR]
Main Results: The abstract reports a large false-alarm reduction at the same recall level, but exact reuse needs repaired table/figure evidence. [NEEDS TABLE REPAIR]
Contribution Wording: Three-part contribution pattern: dataset construction, learning method, quantitative/qualitative evaluation.
Limitations or Scope Boundaries: The abstract promises database/tool sharing, but local source root lacks the database/model/web-service artifacts. [NEEDS ARTIFACT]
Reusable Writing Pattern: Tie a practical audit bottleneck to a measurable false-positive problem, then present a prioritization system rather than a full automatic vulnerability detector.
Relevance to Our Paper: Useful as a baseline and framing reference for VCC identification, but not sufficient evidence for affected versions.
Do Not Borrow: Do not borrow false-positive reduction numbers or benchmark claims until tables and artifact provenance are verified.
Agent Evidence Anchors: raw_extraction/section_text/01_abstract.txt; raw_extraction/source_static_inventory.txt.
""",
"02_introduction.txt": common + """Opening Context: The paper starts from increasing vulnerability discovery and insufficient audit manpower.
Why the Problem Matters: Missed vulnerabilities enter production because exhaustive manual audit is not feasible.
Concrete Pain Point: Metric-based scanners produce many false positives, so reviewers need prioritization, not just more warnings.
Motivating Example: The paper motivates VCCFinder as a way to flag suspicious commits for focused review; concrete case examples appear in evaluation/case-study sections.
Prior Work Framing: It positions itself against code-metric scanners and prior vulnerability prediction/mining studies.
Why Prior Work Is Insufficient: Code metric tools lack enough context, while prior mapping efforts did not provide the same large-scale CVE-to-GitHub vulnerable commit database.
Technical Challenges: Data labeling, noisy VCC heuristics, heterogeneous features, scalability, and explainability.
Key Insight: Commit metadata and history/context features complement code metrics when ranking commits for audit.
System / Method Preview: CVE/fixing-commit collection -> blame heuristic to identify VCCs -> feature extraction -> generalized bag-of-words/SVM classifier -> audit prioritization.
Contribution List: database of vulnerable commits, SVM-based suspicious commit classifier, evaluation and lessons learned.
Claim-Evidence Structure: practical audit bottleneck -> dataset construction -> ML ranking method -> precision/recall comparison and case studies.
Agent Evidence Anchors: raw_extraction/section_text/02_introduction.txt; raw_extraction/section_text/04_methodology.txt; raw_extraction/section_text/06_evaluation.txt.
Paragraph Map:
P1: vulnerability/audit scalability context; evidence type is motivation.
P2: false-positive burden of static metric tools; evidence type is problem statement.
P3: proposed repository-metadata + code-metric method; evidence type is method preview.
P4: contributions and claimed sharing; evidence type includes artifact claim needing verification. [NEEDS ARTIFACT]
Reusable Moves: Frame ML as prioritization for human audit, not as replacing expert review.
Risks for Our Paper: Avoid treating VCCFinder as affected-version identification; it ranks commits and constructs VCC labels.
""",
"03_background_motivation.txt": common + """Domain Concepts Introduced: CVE, fixing commit, vulnerability-contributing commit (VCC), Git blame, code metrics, repository metadata, commit-level features, SVM classifier.
Task Definition: Given project histories and a training database of vulnerable/non-vulnerable commits, rank commits likely to have introduced vulnerabilities.
Threat Model / Assumptions: This is an audit-assistance setting, not an exploit/threat model; it assumes Git history and CVE/fix links are available.
Motivating Case: Code audit triage under false-positive overload.
Why the Case Is Chosen: It connects vulnerability discovery pressure to a measurable prioritization task.
Definitions Needed by Readers: VCC, unclassified commit, historical/test split, precision/recall, feature scope.
How Background Leads to Method: Related work and introduction motivate combining source-level metrics with metadata and commit-history features.
Writing Pattern: Define the practical bottleneck first, then introduce data labeling and ML only as the mechanism for ranking.
Relevance to Our Paper: Helps separate VCC identification and prioritization from affected-version propagation.
Agent Evidence Anchors: raw_extraction/section_text/02_introduction.txt; raw_extraction/section_text/03_related_work.txt.
""",
"04_problem_definition.txt": common + """Input: GitHub C/C++ project histories, CVE references/fixing commits, commit diffs, code metrics, and repository metadata as stated in the paper. The local source root does not include the full database. [NEEDS ARTIFACT]
Output: ranked suspicious commits or VCC candidates for manual audit; local adapted script 2_gen_vuln_version.py also computes vulnerable-version tags from selected VCCs, but that is source-layer evidence and not the core paper claim.
Objects / Entities: CVEs, fixing commits, VCCs, unclassified commits, features, SVM model, precision/recall curves, Flawfinder baseline.
Formal Definitions: Precision/recall and feature mappings are described in paper text; formulas/layout are not repaired. [NEEDS FORMULA REPAIR]
Objective: Reduce manual audit effort by finding likely vulnerability-contributing commits with lower false-positive burden.
Constraints: Limited to labeled CVEs/projects and C/C++ feature extraction; language transfer requires retraining per paper limitations.
Evaluation Target: temporal split over historical/test data and comparison to Flawfinder.
Boundary Conditions: Unknown vulnerabilities in the database make true positives lower-bound and false positives upper-bound, per limitations.
What Is Not Solved: Does not guarantee that flagged commits reveal the underlying vulnerability; still requires expert audit.
Reusable Formalization Pattern: Treat vulnerability search as a ranking/prioritization problem with explicit label noise and lower/upper-bound caveats.
""",
"05_method.txt": common + """System Overview: VCCFinder builds a vulnerable commit database and learns a classifier over heterogeneous code/repository features to prioritize audit targets.
Pipeline Stages:
1. Select GitHub C/C++ projects and collect CVEs/fixing commits.
2. Use a blame heuristic to map fixing commits to VCCs.
3. Extract project/author/commit/file/function/text features.
4. Convert heterogeneous features into a generalized bag-of-words representation.
5. Train a linear SVM classifier.
6. Use classifier scores/explanations to prioritize commits for audit.
Core Algorithm: The paper's VCC heuristic ignores documentation, blames deleted lines, blames neighbors around inserted blocks, then marks the most-blamed commit(s) as vulnerable-contributing.
Data Structures: CVE/commit/repository database tables are mentioned by the paper, but local dump/database is absent. [NEEDS ARTIFACT]
Model / Agent Components: linear SVM; no LLM/agent component.
Design Choices: temporal split for realistic evaluation, generalized bag-of-words for heterogeneous features, linear SVM for scalability/explainability.
Why Each Choice Is Needed: Heterogeneous metadata/code features need one representation; audit teams need interpretable ranking, not opaque binary alerts.
Failure Handling: Label noise from blame heuristic and unknown vulnerability labels are explicitly discussed as limitations.
Complexity / Cost Discussion: The paper emphasizes scalability to large repositories, but runtime reproduction is not checked. [EXECUTION NOT REQUESTED]
Pseudocode or Algorithm Blocks: no formal pseudocode block was extracted; heuristic is textual. [NEEDS EVIDENCE]
Static Reproducibility Signals: local source has 1_vccfinder.py, abstract_szz.py, comment_parser.py, 2_gen_vuln_version.py, config.py; source_static_symbols.json confirms VCCFinder, patchCommit, AbstractSZZ, BlameData, GitLog symbols.
Agent Evidence Anchors: raw_extraction/section_text/04_methodology.txt; raw_extraction/section_text/05_learning_based_detection.txt; raw_extraction/source_static_inventory.txt.
Writing Pattern: Put data construction before model design; make label-generation uncertainty explicit before evaluation.
""",
"06_experiments.txt": common + """Research Questions: The paper evaluates whether combined code/metadata features predict VCCs, how VCCFinder compares to Flawfinder, which commits it flags, and what lessons/features emerge.
Datasets: Paper states 66 C/C++ GitHub projects, 718 CVEs, 640 VCCs, and 169,502 unclassified commits; exact numbers are extracted from text/table but need table verification for citation-ready use. [NEEDS TABLE REPAIR]
Baselines: Flawfinder and feature-subset classifiers.
Metrics: precision/recall curves, false positives/manual-review burden, qualitative case studies.
Experimental Protocol: temporal split around 2011 into historical training and future test data.
Implementation Details: paper-level implementation uses feature extraction and SVM; local code package appears adapted and incomplete relative to paper's full artifact. [NEEDS ARTIFACT]
Hyperparameters / Settings: SVM settings and binning details are partly described; exact model config not locally verified. [NEEDS ARTIFACT]
Hardware / Environment: not established from local source; no dependency file found. [NEEDS ARTIFACT]
Static Reproducibility Materials: local Python scripts exist, but database/model/evaluation scripts are missing or incomplete relative to paper claims.
Execution Status: [EXECUTION NOT REQUESTED]
What Is Measured: VCC prediction/ranking quality and comparison to Flawfinder.
What Is Not Measured: affected versions as full release/tag ranges; local execution/regeneration.
Agent Evidence Anchors: raw_extraction/section_text/06_evaluation.txt; raw_extraction/tables/; raw_extraction/figures/; raw_extraction/source_static_inventory.txt.
Writing Pattern: Combine quantitative curves/tables with qualitative review of flagged commits.
""",
"07_evaluation.txt": common + """Main Results: The paper reports VCCFinder outperforms Flawfinder and reduces false alarms at comparable recall; exact numeric reuse requires table/figure repair. [NEEDS TABLE REPAIR]
Per-RQ Findings: Combined features outperform code-only/meta-only feature sets; case studies illustrate true positives and flagged unclassified commits; Flawfinder comparison motivates reduced manual review.
Ablation: Feature-set comparison acts as an ablation-style analysis; exact curves require figure extraction. [NEEDS FIGURE EXTRACTION]
Sensitivity Analysis: Not clearly isolated as parameter sensitivity. [NEEDS EVIDENCE]
Case Study: Evaluation includes manually discussed flagged commits; use structurally, not as copied examples, unless page/figure context is verified.
Efficiency: Audit burden is expressed as number of commits flagged for review; exact numbers need repaired table/figure evidence. [NEEDS TABLE REPAIR]
Error Analysis: Limitations discuss VCC mapping error rate and unknown true vulnerabilities; local artifact does not validate those estimates. [NEEDS ARTIFACT]
Statistical / Validity Notes: Paper uses statistical tests for features and discusses lower/upper-bound interpretation of unknown labels.
How Claims Are Supported: paper text, tables, and figures; local code only partially aligns and does not reproduce results. [EXECUTION NOT REQUESTED]
Unsupported or Weakly Supported Claims: any exact performance number, false-alarm reduction, database completeness, or released benchmark status without artifact/citation verification.
Agent Evidence Anchors: raw_extraction/section_text/06_evaluation.txt; raw_extraction/section_text/08_limitations.txt; raw_extraction/tables/table_index.txt; raw_extraction/figures/figure_index.txt.
Writing Pattern: Use precision-recall curves and case studies to connect model ranking to analyst workload.
""",
"08_limitations_ethics.txt": common + """Stated Limitations: limited project/language scope; heuristic VCC mapping error; unknown vulnerabilities in unlabeled commits; flagged commits still require expert review.
Threats to Validity: label noise, incomplete ground truth, limited language generalization, potential dataset bias toward projects with CVEs.
Ethical Considerations: The paper is defensive audit assistance; no detailed responsible-disclosure protocol was extracted. [NEEDS EVIDENCE]
Security / Misuse Discussion: Focuses on vulnerability discovery support; misuse discussion not explicitly extracted. [NEEDS EVIDENCE]
Responsible Disclosure: [NEEDS EVIDENCE]
Scope Boundaries: C/C++ GitHub projects; retraining needed for other languages; no guarantee that flagged commits expose vulnerability root cause.
Writing Pattern: Strong limitations section ties dataset noise directly to metric interpretation.
Relevance to Our Paper: Particularly useful for discussing imperfect VCC labels and why downstream affected-version inference must account for label uncertainty.
""",
"09_figures_tables.txt": common + """Figure / Table Inventory:
- Table records are raw/caption-neighbor only and not citation-ready. [NEEDS TABLE REPAIR]
- Figure records include caption/context and some page crops, not precise figure crops. [NEEDS FIGURE EXTRACTION]

For each figure/table:
ID: see raw_extraction/tables/table_index.txt and raw_extraction/figures/figure_index.txt
Agent Evidence Unit ID: generated by build_agent_index.py.
Purpose: feature inventory/statistical analysis, dataset split, detection performance, Flawfinder comparison, lessons/take-aways.
Evidence Shown: qualitative and quantitative evidence as extracted from text/captions; exact values require repair.
Placement in Argument: methodology feature definition -> evaluation dataset -> performance curves/tables -> take-away synthesis.
Extraction Confidence: partial.
Repair Needed: [NEEDS TABLE REPAIR]; [NEEDS FIGURE EXTRACTION]; [NEEDS LAYOUT BLOCK EXTRACTION]
Citation Readiness: low for exact numeric claims.
Figure Readiness: partial/low because page crops are not precise figure crops.
Design Pattern: Use a compact feature table plus precision-recall curves to connect data/model to audit workload.
Could Inspire Our Paper? yes, structurally; no direct numeric/visual reuse before repair.
Required Figures for Our Paper: [NEEDS EVIDENCE] depends on our own verified results.
""",
"10_writing_patterns.txt": common + """Best Structural Moves:
- Practical audit bottleneck first, then data construction, then ML model.
- Make noisy-label construction explicit instead of hiding it.
- Use temporal split for realistic prediction framing.
- Pair quantitative precision/recall with qualitative case studies.

Best Transition Moves:
- False positives in static tools -> need prioritization -> CVE-to-commit database -> learned ranking.
- Feature heterogeneity -> generalized bag-of-words -> linear SVM for scalability/explainability.

Best Contribution Wording Pattern:
- Dataset + method + evaluation/lessons, each tied to a concrete reuse value.

Best Method Overview Pattern:
- First explain how labels are obtained, then how features/models consume them.

Best Experiment Framing Pattern:
- Use historical/test split and compare against a familiar tool to translate model metrics into audit workload.

Useful Phrases to Paraphrase Structurally:
- "assist code audits" as prioritization
- "vulnerability-contributing commits" as a label object
- "lower bound true positives / upper bound false positives" as validity caveat

Patterns to Avoid:
- Do not present VCCFinder as a complete vulnerability discovery replacement.
- Do not cite exact figures until table/figure repair.
- Do not claim local artifact reproduces the CCS results.
""",
"11_relevance_to_our_paper.txt": common + """Direct Relevance: high for VCC identification, CVE-to-fix mapping, blame heuristics, and ML-assisted vulnerability audit triage.
Indirect Relevance: useful for affected-version research as an upstream commit-origin signal, with explicit label-noise caveats.
Useful for Which Section: related work, baseline discussion, motivation for version-level reasoning beyond VCC labels, evaluation caveats.
Comparable Task Elements: CVE/fixing commit mapping, VCC inference, repository-history features, temporal evaluation.
Comparable Method Elements: blame heuristic, feature extraction, classifier ranking.
Comparable Evaluation Elements: precision/recall, baseline comparison, case study, limitations from incomplete labels.
What We Can Borrow Structurally: dataset construction narrative, noisy-label caveat, audit-workload framing, feature-ablation style.
What We Cannot Borrow: exact performance claims, database completeness, trained model behavior, or affected-version conclusions.
Evidence Needed Before Use: repaired tables/figures, artifact/database verification, citation verification, and clear task-boundary statement.
Priority: high
""",
"12_artifact_consistency.txt": common + """Paper Claims:
- VCCFinder builds a CVE-to-VCC database and uses code metrics plus repository metadata to train an SVM classifier.
- Paper says the database/tool/service will be shared.

Implemented Components:
- 1_vccfinder.py defines VCCFinder and patchCommit classes and statically imports GitPython/unidiff/config/abstract_szz.
- abstract_szz.py defines AbstractSZZ and BlameData with blame/diff parsing surfaces.
- comment_parser.py parses comments across language types and invokes srcml for some source types.
- 2_gen_vuln_version.py maps selected VCCs/fix commits to vulnerable tags using GitLog utilities.
- log_generation.py defines GitLog methods for git log/diff/tag operations.

Unimplemented or Stubbed Components: full model-training pipeline, feature extraction table generation, SVM model artifacts, database dump, and web service are not present in the observed local source root. [NEEDS ARTIFACT]
Dataset Availability: not present locally except small txt files with unclear semantics. [NEEDS ARTIFACT]
Benchmark / Evaluation Scripts Visible by Static Inspection: not enough to reproduce paper-level evaluation; only adapted scripts are visible. [NEEDS ARTIFACT]
Static Reproduction Instructions or Missing Instructions: README/dependency instructions are absent. [NEEDS ARTIFACT]
Config Files: config.py exists but contains empty directory variables.
Environment Constraints: imports imply GitPython, unidiff, tqdm, srcml, and git usage, but dependencies were not installed or executed. [EXECUTION NOT REQUESTED]
Paper-Code Mismatches:
- Paper's core ML/SVM/database artifact is not visible in the local source root.
- Local package includes vulnerable-version generation script, which is not a central VCCFinder paper contribution but may be an adaptation for affected-version baselines.
- README is absent, preventing artifact provenance verification. [NEEDS ARTIFACT]
Engineering Lessons for Our Paper: keep baseline artifact roles separated: original paper method vs locally adapted affected-version scripts.

Consistency Check:
Claim: VCCFinder maps fix commits to VCCs using blame-like heuristics.
Paper Location: methodology section.
Artifact Evidence: 1_vccfinder.py, abstract_szz.py, comment_parser.py, source_static_symbols.json.
Source Evidence: raw_extraction/source_static_inventory.txt.
Consistency: partially supported by static inspection.
Analysis Mode: static-only.
Use in Our Paper: yes, with caution.

Claim: VCCFinder trains/evaluates SVM classifier and reduces false positives.
Paper Location: learning/evaluation sections.
Artifact Evidence: no visible training/model/evaluation artifact in local root. [NEEDS ARTIFACT]
Source Evidence: local scripts do not demonstrate paper-level ML pipeline by static inventory.
Consistency: unsupported locally; paper-only.
Analysis Mode: static-only.
Use in Our Paper: paper-level related work only, not artifact-backed.
""",
"13_completeness_audit.txt": common + """Raw Extraction:
- PDF text extracted: yes
- Page text extracted: yes, page count 12
- Section text extracted: yes, section file count 10
- Agent index exists: yes after build_agent_index.py
- Extraction profile exists: yes after build_agent_index.py
- Layout blocks extracted: missing/not attempted
- References extracted: yes/uncertain, citation metadata unverified
- Table extraction: caption-neighbor/plain-text only; not citation-ready
- Figure extraction: caption/context plus page crops for detected captions; not precise figure-ready
- Formula/algorithm/prompt extraction: formula/algorithm not repaired; prompt not detected/not applicable
- OCR needed: no

Section Analysis:
- 00_meta.txt through 12_artifact_consistency.txt: complete
- Are analysis files section-oriented enough for writing? yes, with explicit weak-evidence labels

Source / Artifact Static Analysis:
- Source inventory exists: yes
- README/config inspected: config yes; README missing [NEEDS ARTIFACT]
- Main entrypoints inspected: yes, by filename and AST symbol inventory
- Runtime behavior: [EXECUTION NOT REQUESTED]

Writing Readiness:
- Abstract support: strong
- Introduction support: strong
- Background/motivation support: strong
- Method support: strong for paper-level method; partial for local implementation
- Experiment/evaluation support: partial because exact tables/figures and artifacts need repair/verification
- Limitations support: strong
- Related work support: partial

Known Gaps:
- [NEEDS TABLE REPAIR]
- [NEEDS FIGURE EXTRACTION]
- [NEEDS LAYOUT BLOCK EXTRACTION]
- [NEEDS FORMULA REPAIR]
- [NEEDS ALGORITHM REPAIR]
- [NEEDS CITATION VERIFICATION]
- [NEEDS ARTIFACT]
- [EXECUTION NOT REQUESTED]

Usefulness Grade: high for related-work, baseline framing, and label-noise discussion; partial for quantitative or artifact-backed claims.
""",
"14_section_retrieval_map.txt": common + """For Introduction:
- Read analysis/02_introduction.txt
- Read raw_extraction/section_text/02_introduction.txt
- Useful claims: audit workload and false-positive motivation.
- Must not claim: affected-version coverage.

For Background / Motivation:
- Read analysis/03_background_motivation.txt
- Read raw_extraction/section_text/03_related_work.txt
- Useful claims: VCC terminology and prior-work placement.
- Must not claim: implementation support beyond paper text.

For Method:
- Read analysis/05_method.txt
- Read raw_extraction/section_text/04_methodology.txt and 05_learning_based_detection.txt
- Read raw_extraction/source_static_inventory.txt
- Useful claims: CVE-to-VCC heuristic, feature extraction, SVM ranking.
- Must not claim: local artifact reproduces SVM/database. [NEEDS ARTIFACT]

For Experiments / Evaluation:
- Read analysis/06_experiments.txt and analysis/07_evaluation.txt
- Read raw_extraction/section_text/06_evaluation.txt
- Useful claims: temporal split, Flawfinder comparison structure.
- Must not claim: exact numeric values until table/figure repair. [NEEDS TABLE REPAIR]

For Limitations:
- Read analysis/08_limitations_ethics.txt
- Read raw_extraction/section_text/08_limitations.txt
- Useful claims: label noise, unknown vulnerabilities, language/project limits.
- Must not claim: complete ground truth.

For Related Work:
- Read analysis/11_relevance_to_our_paper.txt
- Read raw_extraction/section_text/03_related_work.txt
- Useful claims: VCCFinder as VCC/audit-prioritization baseline.
- Must not claim: citation metadata before verification. [NEEDS CITATION VERIFICATION]
""",
}

for name, text in files.items():
    (ANALYSIS / name).write_text(text, encoding="utf-8")
